<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Art in Focus',
                'author' => 'Jean Morman Unsworth',
                'publisher' => 'Glencoe/McGraw-Hill',
                'year' => 2000,
                'genre' => 'Art',
                'description' => 'Art in focus: Aesthetics, criticism, history, studio.',
                'cover' => 'covers/ArtInFocus_image.jpg',
                'pdf_path' => 'pdfs/ArtInFocus_Gene_A_Mittler.pdf',
                'pdf_name' => 'ArtInFocus_Gene_A_Mittler.pdf',
            ],
            [
                'title' => 'Contemporary Painting',
                'author' => 'Suzanne Hudson',
                'publisher' => 'Thames & Hudson',
                'year' => 2021,
                'genre' => 'Art',
                'description' => 'Renowned critic and art historian Suzanne Hudson offers an intelligent and original survey of the subject.',
                'cover' => 'covers/ContemporaryPainting_image.jpg',
                'pdf_path' => 'pdfs/ContemporaryPainting_Suzanne_Hudson.pdf',
                'pdf_name' => 'ContemporaryPainting_Suzanne_Hudson.pdf',
            ],
            [
                'title' => 'Patterns',
                'author' => 'Drusilla Cole',
                'publisher' => 'Laurence King Publishing',
                'year' => 2009,
                'genre' => 'Art',
                'description' => 'This stunning picture book chronicles one hundred years of classic patterns.',
                'cover' => 'covers/Patterns_image.jpg',
                'pdf_path' => 'pdfs/Patterns_drusilla_cole.pdf',
                'pdf_name' => 'Patterns_drusilla_cole.pdf',
            ],
            [
                'title' => 'Stages Of Rot',
                'author' => 'Linnea Sterte',
                'publisher' => 'Koguchi Press',
                'year' => 2017,
                'genre' => 'Art',
                'description' => 'An alien desert comes to life around the body of a dying whale.',
                'cover' => 'covers/StagesOfRot_image.jpg',
                'pdf_path' => 'pdfs/StagesOfRot_Linnea_Sterte.pdf',
                'pdf_name' => 'StagesOfRot_Linnea_Sterte.pdf',
            ],
            [
                'title' => 'The Wrong Shoes',
                'author' => 'Tom Percival',
                'publisher' => 'Simon & Schuster Children\'s UK',
                'year' => 2025,
                'genre' => 'Art',
                'description' => 'Will has the wrong shoes – he\'s always known it but doesn\'t know how to change it.',
                'cover' => 'covers/TheWrongShoes_image.jpg',
                'pdf_path' => 'pdfs/TheWrongShoes_Tom_Percival.pdf',
                'pdf_name' => 'TheWrongShoes_Tom_Percival.pdf',
            ],
            [
                'title' => 'Disney\'s World',
                'author' => 'Leonard Mosley',
                'publisher' => 'Stein and Day',
                'year' => 1985,
                'genre' => 'Biography',
                'description' => 'Draws an intimate portrait of the man whose imagination spawned Disney.',
                'cover' => 'covers/DisneysWorldABiography_image.jpg',
                'pdf_path' => 'pdfs/DisneysWorldABiography_LeonardMosley.pdf',
                'pdf_name' => 'DisneysWorldABiography_LeonardMosley.pdf',
            ],
            [
                'title' => 'Gas Man',
                'author' => 'Colin Black',
                'publisher' => 'HarperCollins Publishers',
                'year' => 2022,
                'genre' => 'Biography',
                'description' => 'Razor-sharp and forthright biography of life at medicine’s frontline.',
                'cover' => 'covers/GasMan_image.jpg',
                'pdf_path' => 'pdfs/GasMan_ColinBlack.pdf',
                'pdf_name' => 'GasMan_ColinBlack.pdf',
            ],
            [
                'title' => 'Honourable Man My Life In The CIA',
                'author' => 'William Colby',
                'publisher' => 'Simon and Schuster',
                'year' => 1978,
                'genre' => 'Biography',
                'description' => 'Memoir of a veteran intelligence agent and former CIA director.',
                'cover' => 'covers/HonourableManMyLifeInTheCIA_image.jpg',
                'pdf_path' => 'pdfs/HonourableManMyLifeInTheCIA_WilliamColby.pdf',
                'pdf_name' => 'HonourableManMyLifeInTheCIA_WilliamColby.pdf',
            ],
            [
                'title' => 'Leap Year',
                'author' => 'Helen Russell',
                'publisher' => 'Hodder & Stoughton',
                'year' => 2017,
                'genre' => 'Biography',
                'description' => 'How to make big decisions, be more resilient, and change your life.',
                'cover' => 'covers/LeapYear_image.jpg',
                'pdf_path' => 'pdfs/LeapYear_HelenRussell.pdf',
                'pdf_name' => 'LeapYear_HelenRussell.pdf',
            ],
            [
                'title' => 'The Business Of Being Me',
                'author' => 'Issa Rae',
                'publisher' => 'Brilliance Publishing',
                'year' => 2025,
                'genre' => 'Biography',
                'description' => 'A funny and inspiring essay about ambition and creativity.',
                'cover' => 'covers/TheBusinessOfBeingMe_image.jpg',
                'pdf_path' => 'pdfs/TheBusinessOfBeingMe_IssaRae.pdf',
                'pdf_name' => 'TheBusinessOfBeingMe_IssaRae.pdf',
            ],
            [
                'title' => 'Christmas At Hogwarts',
                'author' => 'JK Rowling',
                'publisher' => 'Scholastic/Bloomsbury',
                'year' => 2024,
                'genre' => 'Fantasy',
                'description' => 'With text from one of the most beloved moments in J.K. Rowling\'s bestselling original novel, Harry Potter and the Philosopher\'s Stone... this new illustrated book promises to be the perfect festive treat.',
                'cover' => 'covers/ChristmasAtHogwarts_image.jpg',
                'pdf_path' => 'pdfs/ChristmasAtHogwarts_JK_Rowling.pdf',
                'pdf_name' => 'ChristmasAtHogwarts_JK_Rowling.pdf',
            ],
            [
                'title' => 'Dragon Planet',
                'author' => 'Dan Wells',
                'publisher' => 'Audible Studios',
                'year' => 2019,
                'genre' => 'Fantasy',
                'description' => 'Zero and Nyx are stranded on an unknown planet with no way to communicate, being chased by thieves, and with another storm bearing down on them.',
                'cover' => 'covers/DragonPlanetCover.png',
                'pdf_path' => 'pdfs/DragonPlanet_DanWells.pdf',
                'pdf_name' => 'DragonPlanet_DanWells.pdf',
            ],
            [
                'title' => 'Flammen Sturm',
                'author' => 'Juliette Cross',
                'publisher' => 'Dark Intense',
                'year' => 2025,
                'genre' => 'Fantasy',
                'description' => 'Alles verschlingende Dark Romantasy ab 16 Jahren - Historische Fantasy trifft auf epische Romance im antiken Rom.',
                'cover' => 'covers/Flammensturm_image.jpg',
                'pdf_path' => 'pdfs/FlammenSturm_Juliette_Cross.pdf',
                'pdf_name' => 'FlammenSturm_Juliette_Cross.pdf',
            ],
            [
                'title' => 'Hana Tara Hata',
                'author' => 'Tere Liye',
                'publisher' => 'Sabak Grip Nusantara',
                'year' => 2025,
                'genre' => 'Fantasy',
                'description' => 'Tentang seorang pemilik kekuatan “membaca alam sekitar”. Tentang seorang ibu yang sangat menyayangi anaknya. Rasa sakit. Kehilangan. Pengorbanan. Kebencian. Memaafkan.',
                'cover' => 'covers/HanaTaraHata_image.jpg',
                'pdf_path' => 'pdfs/HanaTaraHata_Tere_Liye.pdf',
                'pdf_name' => 'HanaTaraHata_Tere_Liye.pdf',
            ],
            [
                'title' => 'Storm Signal',
                'author' => 'P L Matthews',
                'publisher' => 'Kindle',
                'year' => 2025,
                'genre' => 'Fantasy',
                'description' => 'Skye\'s tech magic and Zephyra\'s wild air magic don\'t exactly blend. With the storm building—both magical and emotional—the sisters will have to figure out how to work together.',
                'cover' => 'covers/StormSignal_image.jpg',
                'pdf_path' => 'pdfs/StormSignal_P_L_Matthews.pdf',
                'pdf_name' => 'StormSignal_P_L_Matthews.pdf',
            ],
            [
                'title' => '1962The War That Wasnt',
                'author' => 'Shiv Kunal Verma',
                'publisher' => 'Aleph Book Company',
                'year' => 2016,
                'genre' => 'History',
                'description' => 'In this definitive account of the conflict, Shiv Kunal Verma takes us on an uncomfortable journey through one of the most disastrous episodes of independent India\'s history.',
                'cover' => 'covers/1962TheWarThatWasnt_image.jpg',
                'pdf_path' => 'pdfs/1962TheWarThatWasnt_ShivKunalVerma.pdf',
                'pdf_name' => '1962TheWarThatWasnt_ShivKunalVerma.pdf',
            ],
            [
                'title' => 'Confessions Of An Actor',
                'author' => 'Laurence Olivier',
                'publisher' => 'Simon & Schuster',
                'year' => 1982,
                'genre' => 'History',
                'description' => 'An autobiography by the English actor discussing his theatrical and film career and offering a candid account of his personal life.',
                'cover' => 'covers/ConfessionsOfAnActor_image.jpg',
                'pdf_path' => 'pdfs/ConfessionsOfAnActor_LaurenceOlivier.pdf',
                'pdf_name' => 'ConfessionsOfAnActor_LaurenceOlivier.pdf',
            ],
            [
                'title' => 'Democratic Ideals And Reality',
                'author' => 'Halford John Mackinder',
                'publisher' => 'Henry Holt and Co.',
                'year' => 1919,
                'genre' => 'History',
                'description' => 'He argued that interior Asia and eastern Europe were the geographic keys to world power, known as the Heartland theory.',
                'cover' => 'covers/DemocraticIdealsAndReality_image.jpg',
                'pdf_path' => 'pdfs/DemocraticIdealsAndReality_HalfordJohnMackinder.pdf',
                'pdf_name' => 'DemocraticIdealsAndReality_HalfordJohnMackinder.pdf',
            ],
            [
                'title' => 'Le Mariage',
                'author' => 'Dorothy West',
                'publisher' => 'Doubleday',
                'year' => 1995,
                'genre' => 'History',
                'description' => 'A novel set in the 1950s about a Black bourgeois family in Martha\'s Vineyard facing social tension after an interracial engagement.',
                'cover' => 'covers/LeMariage_image.jpg',
                'pdf_path' => 'pdfs/LeMariage_DorothyWest.pdf',
                'pdf_name' => 'LeMariage_DorothyWest.pdf',
            ],
            [
                'title' => 'The Egypt Code',
                'author' => 'Robert Bauval',
                'publisher' => 'Disinformation Company Limited',
                'year' => 2008,
                'genre' => 'History',
                'description' => 'An investigation into astronomy and Egyptian monuments, proposing a vast sky-ground correlation for the Memphite-Heliopolis region.',
                'cover' => 'covers/TheEgyptCode_image.jpg',
                'pdf_path' => 'pdfs/TheEgyptCode_RobertBauval.pdf',
                'pdf_name' => 'TheEgyptCode_RobertBauval.pdf',
            ],
            [
                'title' => 'Everything Changes But You',
                'author' => 'Sarah Bennett',
                'publisher' => 'Boldwood Books Ltd.',
                'year' => 2025,
                'genre' => 'Romance',
                'description' => 'A dreamy seaside romance following Issy and Liam, balancing personal growth and love.',
                'cover' => 'covers/EverythingChangesButYou_image.png',
                'pdf_path' => 'pdfs/EverythingChangesButYou_SarahBennett.pdf',
                'pdf_name' => 'EverythingChangesButYou_SarahBennett.pdf',
            ],
            [
                'title' => 'Fake AChance On Me',
                'author' => 'Rebecca Chase',
                'publisher' => 'Kindle',
                'year' => 2025,
                'genre' => 'Romance',
                'description' => 'A fake-dating romance involving a rugby player, emotional healing, and unexpected feelings.',
                'cover' => 'covers/FakeAChanceOnMe_image.jpg',
                'pdf_path' => 'pdfs/FakeAChanceOnMe_RebeccaChase.pdf',
                'pdf_name' => 'FakeAChanceOnMe_RebeccaChase.pdf',
            ],
            [
                'title' => 'Love PRN',
                'author' => 'Cadence Rush',
                'publisher' => 'Cadence Rush Books',
                'year' => 2025,
                'genre' => 'Romance',
                'description' => 'A nurse struggles with her past while facing the realities of her profession and relationships.',
                'cover' => 'covers/LovePRN_image.jpg',
                'pdf_path' => 'pdfs/LovePRN_CadenceRush.pdf',
                'pdf_name' => 'LovePRN_CadenceRush.pdf',
            ],
            [
                'title' => 'The Number You Are Trying To Reach Is Not Reachable',
                'author' => 'Andara Kirana',
                'publisher' => 'Bukune',
                'year' => 2016,
                'genre' => 'Romance',
                'description' => 'A romance novel with emotional themes and modern communication struggles.',
                'cover' => 'covers/TheNumberYouAreTryingToReachIsNotReachable_image.jpg',
                'pdf_path' => 'pdfs/TheNumberYouAreTryingToReachIsNotReachable_AndaraKirana.pdf',
                'pdf_name' => 'TheNumberYouAreTryingToReachIsNotReachable_AndaraKirana.pdf',
            ],
            [
                'title' => 'Unlucky In Love',
                'author' => 'Kiva Hart',
                'publisher' => 'Abbix Publishing Company',
                'year' => 2025,
                'genre' => 'Romance',
                'description' => 'A small-town romance about second chances, returning home, and rekindled love.',
                'cover' => 'covers/UnluckyInLove_image.jpg',
                'pdf_path' => 'pdfs/UnluckyInLove_KivaHart.pdf',
                'pdf_name' => 'UnluckyInLove_KivaHart.pdf',
            ],
        ];

        foreach ($books as $book) {
            Book::firstOrCreate(
                ['title' => $book['title']],
                $book
            );
        }
    }
}
